service: sdn-dataset-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - es:*
      Resource: "*"

functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  searchDatasets:
    handler: dist/index.handler
    events:
      - http: 'GET /api/datasets/search'
  getDataset:
      handler: dist/index.handler
      events:
        - http: 'GET /api/datasets/{proxy+}'
