service: sdn-dataset-api

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: .env

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - es:*
      Resource: "*"
  enviroment:
    SDN_ACCESS_KEY: ${env:SDN_ACCESS_KEY}

functions:
  app:
    handler: dist/api/index.handler
    events:
      - http:
          path: /
          method: any
  searchDatasets:
    handler: dist/api/index.handler
    events:
      - http:
          paht: /api/datasets/search
          method: get
          request:
            parameters:
              querystrings:
                q: false
  getDataset:
    handler: dist/api/index.handler
    events:
      - http:
          path: /api/datasets/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  bootstrapPipeline:
    handler: dist/api/index.handler
    events:
      - http:
          path: /api/admin/bootstrap_pipeline
          method: post
          authorizer:
            name: authorizer
            identitySource: method.request.header.token
            type: token
  authorizer:
    name: sdn-api-authorizer
    handler: dist/lambda/auth/index.auth
